### ISSUE TITLE
Zotero Citations: could not connect to Zotero. Are you sure it is running?

### ISSUE THREAD

**Issue by Hocnonsense** [mblode/vscode-zotero#14]
Hi... I also got this error in #2 :
![image](https://user-images.githubusercontent.com/48747984/91675289-5d272d80-eb6e-11ea-91ed-0cecf984d082.png)

I downloaded the latest Zotero beta (version 5.0.90-beta.3+e9473caa1), but it didn't work.
What should I do to make it run?

Thanks!

**Comment by Hocnonsense** [comment]
(By the way, I think it is more convenient to cite something like `[author, year](https://doi.org/...)`. After all, It can work WITHOUT any requirement!)

**Comment by danieltomasz** [comment]
I am still getting this error, both on latest Zotero and Zotero  beta :(

**Comment by SorenKF** [comment]
Hi! I am also facing this issue on the latest stable Zotero 5.0.93.

Any news?

**Comment by SorenKF** [comment]
> I am still getting this error, both on latest Zotero and Zotero beta :(

Hey there!

Are you sure you have the BetterBibtex add-on ([https://retorque.re/zotero-better-bibtex/]) installed? :)

**Comment by igravious** [comment]
This issue should *not* be marked closed!

“PSA: as of Zotero 5.0.71, access to the CAYW URL will no longer work from the browser for security reasons; curl and other programmatic access such as from editors access will work.” [](https://retorque.re/zotero-better-bibtex/citing/cayw/)

**Comment by Hocnonsense** [comment]
I'm sorry but this issue was opened by mistake. After I opened `Zotera`, I can add zotero links by vscode key binding.

> However, I rarely use it now because now I find coping the Citation key directly from `Zotero` is easier for me


If you DO think there is an issue, you can open another issue, and describe your demands preciously?

**Comment by igravious** [comment]
eh? yeah. i had install the extension onto a remote machine. did not know vscode could do that. i am going to delete my comment, suggest you do the same :)

**Comment by eascarrunz** [comment]
I am having this problem with WSL2. Does anyone have a fix?

**Comment by nasiegel88** [comment]
Same, I'm wondering if is this WSL2-specific.

**Comment by Viibrant** [comment]
> Same, I'm wondering if this is WSL2-specific.

It may well be, I'm experiencing the same issues.
