### ISSUE TITLE
Zotero Citations: could not connect to...

### ISSUE THREAD

**Issue by atanasj** [mblode/vscode-zotero#2]
Hi,

I am getting the below error:

![image](https://user-images.githubusercontent.com/27214625/62268754-36328f80-b474-11e9-99aa-a7603d332c69.png)

Any idea why this might be happening? Zotero is definitely running... 

Thanks in advance for your help.

**Comment by mblode** [comment]
I think following the "Referencing" section of this blog post may help you get the Zotero picker installed 👍 

https://raphaelkabo.com/blog/posts/markdown-to-word/#referencing

**Comment by atanasj** [comment]
Thanks for that. I followed the instructions, however this still doesn't work. When I try and the extension I am still getting the same error. Additionally, whey I try and run the services as set out in the link you provided, the error I get is `com.automator.runner.xpc is not allowed to send keystrokes.` This is happening in other apps as well, however in `vscode` I get the `electron` pop-up window too. I have a workflow that I have been using for a ages with `Alfred.app` where I run and `.applescript` and paste in the `better-bibtex` key from `Zotero`, which worked similarly to your extension. I think the conflict between `.applescript` and `vscode` is a known issue (see [here](https://github.com/Microsoft/vscode/issues/46762)). See below for the pop-up messages I am getting. 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/27214625/62349876-5598ed80-b544-11e9-9a64-69b4d3d7b888.png">

Here you can see the error message with both `vscode` and `Zotero` open when I try and run the extension. 

![image](https://user-images.githubusercontent.com/27214625/62350121-17e89480-b545-11e9-9a16-9c0c00d3e4ae.png)

Any ideas what I can do to resolve this issues? 

```
| ~ @ uroboros (atanas)
| => sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84
________________________________________________________________________________
| ~ @ uroboros (atanas)
| => code --version
1.36.1
2213894ea0415ee8c85c5eea0d0ff81ecc191529
x64
```

**Comment by mblode** [comment]
I think I've discovered the issue:
Note that as of Zotero 5.0.71, access to this URL will no longer work from the browser for security reasons; curl and other programmatic access will work if you make sure you send a User-Agent header (curl does so by default).

I'm going to work on a fix now 👍

**Comment by atanasj** [comment]
Awesome, thanks! I look forward to the fix!

**Comment by mblode** [comment]
The issue has been fixed by using the latest Zotero beta: https://www.zotero.org/support/dev_builds 🎉

**Comment by atanasj** [comment]
Great, that works now, thanks! However, after inserting the citation the focus changes to `Zotero`. Is that the expected behaviour? It would be great if the focus could return back to `vscode`.
